### ISSUE TITLE
This package looks awesome!

### ISSUE THREAD

**Issue by juliohm** [rdeits/MeshCat.jl#11]
Thanks for the package, I am sure it will be really useful for many researchers!

I tried cloning master and creating the visualization on Linux + Chromium, getting this error about the GPU:

```julia
julia> open(vis)
MeshCat Visualizer at http://127.0.0.1:7000/static/ with path /meshcat

julia> Created new window in existing browser session.
[22602:22632:0305/192007.094718:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
SystemError("opening file /home/juliohm/.julia/v0.6/MeshCat/viewer/static/meshcat.html", 2, nothing)
ERROR: SystemError: opening file /home/juliohm/.julia/v0.6/MeshCat/viewer/static/meshcat.html: No such file or directory
SystemError("opening file /home/juliohm/.julia/v0.6/MeshCat/viewer/static/meshcat.html", 2, nothing)
ERROR: SystemError: opening file /home/juliohm/.julia/v0.6/MeshCat/viewer/static/meshcat.html: No such file or directory
Stacktrace:
 [1] #systemerror#44 at ./error.jl:64 [inlined]
 [2] systemerror(::String, ::Bool) at ./error.jl:64
 [3] open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./iostream.jl:104
 [4] handle_file_request(::HttpCommon.Request, ::HttpCommon.Response) at /home/juliohm/.julia/v0.6/MeshCat/src/servers/zmqserver.jl:24
 [5] (::HttpServer.#on_message_complete#14{HttpServer.Server,HttpServer.Client{TCPSocket},Bool})(::HttpCommon.Request) at /home/juliohm/.julia/v0.6/HttpServer/src/HttpServer.jl:427
 [6] on_message_complete(::Ptr{HttpParser.Parser}) at /home/juliohm/.julia/v0.6/HttpServer/src/RequestParser.jl:113
 [7] http_parser_execute(::HttpParser.Parser, ::HttpParser.ParserSettings, ::Array{UInt8,1}) at /home/juliohm/.julia/v0.6/HttpParser/src/HttpParser.jl:115
 [8] process_client(::HttpServer.Server, ::HttpServer.Client{TCPSocket}, ::Bool) at /home/juliohm/.julia/v0.6/HttpServer/src/HttpServer.jl:389
 [9] (::HttpServer.##7#8{HttpServer.Server,Bool})() at ./task.jl:335
```

**Comment by rdeits** [comment]
I think the GPU issue might just be a red herring--the more important error is that it can't find `meshcat.html`. That's just because you're missing the git submodule that contains all the HTML and JS files. Can you please try `Pkg.build("MeshCat")` and then try again? (`Pkg.clone()` doesn't do the `build()` step automatically).

**Comment by juliohm** [comment]
This is my favorite package of the year already, everything is working now. I would like to add extensions to my GeoStats.jl package in order to visualize 3D models on the browser. Do you recommend a tutorial or documentation that I could follow? I will check the Javascript counterpart as well.

**Comment by rdeits** [comment]
That's great to hear, thank you! 

I'm afraid there isn't a lot of documentation for development, but I'm happy to do what I can. The easiest way to draw your geometries would be to use the existing supported types. If you can create a mesh (using the various `AbstractMesh` types from GeometryTypes.jl)`, then you should be able to visualize it here without any extra work. For example, some pseudocode might be:

```julia
function MeshCat.setobject!(vis::Visualizer, data::GeoStatsData)
  mesh = construct_mesh_from_geo_stats(data)
  setobject!(vis, mesh)
end
```

You can do pretty interesting things just by constructing meshes, such as visualizing level sets of functions: https://github.com/rdeits/MeshCat.jl#complex-geometries

If you need to visualize something other than a triangle mesh or one of the other supported types, then that will require a bit more work. The way MeshCat.jl works is that every geometry or material is converted into a plain `Dict` by the `MeshCat.lower()` function. The format of the Dict is exactly the native JSON serialization used by three.js, so anything that three.js can render is possible from MeshCat (with some work). For example, I know that three.js supports images, animations, and skinned models, none of which are exposed in MeshCat.jl yet. 

There's not much documentation on that JSON format, but there is some here: https://github.com/mrdoob/three.js/wiki/JSON-Geometry-format-4 . I've also had to do a bit of reverse-engineering to figure out all of the supported geometry types. Anyway, let me know what you want to render and I'll try to point you in the right direction.

**Comment by juliohm** [comment]
Thanks @rdeits, that is awesome, I will try to dive in next quarter when I find some time, the idea of visualizing everything on the browser without the need to install a single dependency is just great. Building on top of three.js is also a very clever move.

**Comment by juliohm** [comment]
I don't know if it is in your plans already, but because we have WriteVTK.jl, another intermediate step that would work for many users would be to convert data to a VTK mesh first and then provide in MeshCat.jl a converter from VTK to three.jl. It may be a lot of work, but just sharing some random thoughts.

**Comment by rdeits** [comment]
Oh, cool, I hadn't heard of WriteVTK.jl, thanks for sharing that. That could certainly work. Please let me know if this ends up being a direction you'd like to pursue.

**Comment by juliohm** [comment]
VTK is the de-facto format for scientific visualization. WriteVTK.jl is great for exporting 3D data from Julia for visualization in ParaView. The part I don't like about my current workflow is having to open a heavy program like ParaView manually and operating there instead of in Julia. I'd rather go for something like MeshCat.jl that works on the browser and is script-able.

Other related packages are [VTKDataTypes.jl](https://github.com/mohamed82008/VTKDataTypes.jl) and [VTKDataIO.jl](https://github.com/mohamed82008/VTKDataIO.jl). I never used these packages myself, but  they attempt to define Julia types for the corresponding VTK types, which is a big accomplishment by itself already.

Many directions to move forward.
