### ISSUE TITLE
Badly degraded performance with latest WebIO

### ISSUE THREAD

**Issue by tkoolen** [rdeits/MeshCat.jl#118]
Upgrading from WebIO 0.8.6 to 0.8.8 (with MeshCat master) seems to cause geometry loading to become much slower. If you load Atlas, each individual link pops up about half a second after the other. I'll try to make a repro later, but I'm a little pressed for time right now.

CC: @travigd.

**Comment by travigd** [comment]
It looks like we're publishing un-minified JS. Can you do...

```julia
]dev WebIO
# (also make sure WebIO is checked out to master if you've dev'd before)
WebIO.bundlejs()
```

and see if that makes it better? That will build minified JS.

**Comment by travigd** [comment]
Without a repro I'm not sure how to debug this.

**Comment by tkoolen** [comment]
Thanks very much for the help and sorry for the lack of a repro. I seem to no longer be able to reproduce the degraded performance with 0.8.8 myself after `free`ing WebIO again... I guess I'll close this and reopen if I can actually reproduce again. Sorry about the noise.
