### ISSUE TITLE
Use FFMPEG.jl to provide a more uniform ffmpeg experience

### ISSUE THREAD

**Issue by rdeits** [rdeits/MeshCat.jl#121]
And update `convert_frames_to_video` to use that version of `ffmpeg`. 

This should fix the uneven performance of video encoding across platforms.

**Comment by dehann** [comment]
Hi, I just happened to see this, this is what I have been doing (maybe its useful for command flags etc)
https://github.com/JuliaRobotics/IncrementalInference.jl/blob/77e21ff4f145c83a3c7609eb3efcffbbb53e8717/src/CliqStateMachineUtils.jl#L284
