### ISSUE TITLE
Orbit Controls - Panning

### ISSUE THREAD

**Issue by ferrolho** [rdeits/MeshCat.jl#132]
After updating three.js to v110 (https://github.com/rdeits/MeshCat.jl/pull/131) the orbit controls have now a different panning default behaviour:

> .screenSpacePanning : Boolean
> Defines how the camera's position is translated when panning. If true, the camera pans in screen space. Otherwise, the camera pans in the plane orthogonal to the camera's up direction. Default is false.

Relevant docs: https://threejs.org/docs/#examples/en/controls/OrbitControls.screenSpacePanning

Personally, I'd rather have the old behaviour. Is there any way, from MeshCat.jl, we can set the above boolean to `false`?

**Comment by rdeits** [comment]
Ah, whoops, I just missed that. We should just restore the old behavior in the `meshcat` javascript repo and then pull that into MeshCat.jl again.
