### ISSUE TITLE
Overloading CPU on version 0.10

### ISSUE THREAD

**Issue by bjack205** [rdeits/MeshCat.jl#157]
I'm getting excessive CPU usage on MeshCat version 0.10. 
I'm running Julia v1.4.1 and had this problem on Ubuntu 18.06 and Ubuntu 20.04. Switching down to version 0.9 fixed the problem.

Computer Specs:
OS: Ubuntu 20.04 LTS
CPU: i9-9900 @ 3.10 GHz x 16
Graphics: Quadro P1000
Memory: 32 GB
Model: Dell Precision 3431 Workstation

Based on my status monitor, it seems to be hogging an entire thread / CPU:

![Screenshot from 2020-05-13 15-54-00](https://user-images.githubusercontent.com/9097986/81874076-fd126a00-9531-11ea-811e-01c549be5d5c.png)
![Screenshot from 2020-05-13 15-54-38](https://user-images.githubusercontent.com/9097986/81874126-13b8c100-9532-11ea-9f90-d59f7253d9bc.png)

It runs like this all the time, even when I'm not doing anything with MeshCat or interacting with the visualizer.

Let me know if you need me to send any more diagnostics.

**Comment by rdeits** [comment]
That's really interesting. I can't reproduce it on master--I'm seeing 0% idle CPU in Chrome on Ubuntu 18.04 with the visualizer open. 

Can you tell me exactly what steps you took to trigger the problem? I would also be interested to see if you also see the problem on `master`. You can do `]add MeshCat#master` .

**Comment by rdeits** [comment]
@bjack205 are you still having this problem? I still haven't seen it locally, but I'm interested in understanding what's happening on your system.

**Comment by bjack205** [comment]
I did some more diagnostics and it seems to be a problem with Chrome, not MeshCat. It worked find with Blink and Firefox. I reset Chrome to default settings and it magically fixed it... not sure what the problem was :man_shrugging:
