### ISSUE TITLE
How to toggle the background?

### ISSUE THREAD

**Issue by PikaPei** [rdeits/MeshCat.jl#173]
First, it's really awesome work!
But I have no idea how to hide background without using the control panel.
I have tried the following commands, but they are no effects:
```
setvisible!(vis["/Background"], false)
setprop!(vis["/Background"], "top_color", false)
setprop!(vis["/Background"], "bottom_color", false)
```

Would someone help me?

**Comment by rdeits** [comment]
Oh, good point. That will work just as soon as #176 is merged.
