### ISSUE TITLE
Can this package connect to public IP?

### ISSUE THREAD

**Issue by PikaPei** [rdeits/MeshCat.jl#174]
Currently, when using `vis = Visualizer()`, it will connect to localhost.
I just wonder whether it can connect to other IP or not?
I tried the following code but found no effect.
```
using Sockets
vis = Visualizer(MeshCat.CoreVisualizer(IPv4(0)), ["meshcat"])
```
Thank you!

**Comment by rdeits** [comment]
That should have worked. It looks like I'm just accidentally dropping the `host` parameter when starting the Mux.jl server. I'll fix that as soon as I can.

**Comment by PikaPei** [comment]
Thank you for such a quick reply and fix. I'll look forward to the new release!
