### ISSUE TITLE
Point colors and Gouraud shading ?

### ISSUE THREAD

**Issue by j-fu** [rdeits/MeshCat.jl#182]
Hi,  would it be possible to support point colors and Gouraud shading ? I  researched the code and think it is currently not supported. If this would be there, MeshCat could be quite useful for FEM visualization.

**Comment by rdeits** [comment]
It looks like Three.js has all the right components, so I just needed to update MeshCat to send the right data. I've created a prototype implementation in https://github.com/rdeits/MeshCat.jl/pull/183 . Does that look like what you would need?

**Comment by j-fu** [comment]
Looks good ! I was quite sure that three.js must have it. Surprised now that it  seems to be that easy to add to MeshCat.

However from a practical point of view for the use case I have in mind it would be more interesting   to be able to supply a color map (or color lookup table) and to have a vector of data values in the point metadata which point into this color map. Short googling tells me that three.js supports this as well
(see e.g.  https://threejs.org/examples/webgl_geometry_colors_lookuptable.html).

Another interesting case in this direction (with less priority) is to alternatively have the same mechanism for face colors, i.e. a data value per face pointing into the face color map.
