### ISSUE TITLE
I got MeshCat working with 1.5.2. Any interest in that?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [rdeits/MeshCat.jl#184]

**Comment by ferrolho** [comment]
Yes! :+1:

**Comment by valerocar** [comment]
Hi. I am interested. I have been having problems using meshcat with Julia 1.5.2.

What is you advice?

**Comment by PetrKryslUCSD** [comment]
I'm afraid I don't have a general solution for all platforms. I did get it working on Windows: all it takes is to update dependencies.

**Comment by valerocar** [comment]
Thanks!

**Comment by rdeits** [comment]
Sorry for missing this! I just posted an updated PR over in #187 and it's working fine for me on Linux with Julia 1.5.2 and 1.5.3. I'll make sure it works on Windows (via appveyor) before merging it.
