### ISSUE TITLE
Video conversion kwargs and bug fix for Windows

### ISSUE THREAD

**Issue by janbruedigam** [rdeits/MeshCat.jl#194]
The function `convert_frames_to_video` currently works, but on Windows, the resulting video cannot be played on standard players because they think the video is broken.
A fix that works (I just tried it) is to add the `"-pix_fmt", "yuv420p"` option for the conversion (source: https://stackoverflow.com/questions/34942989/ffmpeg-converted-mp4-videos-are-not-playing-on-windows)

Maybe it would be an even better idea to simply allow passing in additional options to the function with a kwarg containing an array or tuple of strings that is then splatted? That way there are no direct changes to the current functionality but the user has more options available if desired (e.g. resolution ...).

Happy to create a pull request if that makes sense.

**Comment by ferrolho** [comment]
Solved by #247.
