### ISSUE TITLE
Does the Julia interface also support 0MQ?

### ISSUE THREAD

**Issue by ad1t7a** [rdeits/MeshCat.jl#197]
I want to send point cloud data from a C++ library to meshcat. Would a ZMQ interface work? What would be the preferred method to display a point cloud in meshcat using C++?

**Comment by rdeits** [comment]
Yes, that's definitely possible. The folks over at Google Research actually have an open-source example of using meshcat over ZMQ from C++ here: https://github.com/google-research/tiny-differentiable-simulator/tree/master/src/visualizer/meshcat https://github.com/google-research/tiny-differentiable-simulator/blob/master/examples/tiny_urdf_parser_meshcat_example.cpp

**Comment by ad1t7a** [comment]
Thanks a lot!
