### ISSUE TITLE
setobject!() ERROR: 'no method matching setobject'

### ISSUE THREAD

**Issue by PratyushBhattacharya** [rdeits/MeshCat.jl#200]
I'm a greenhorn in Julia & meshcat. I'm trying to run the demo codes in the meshcat GitHUb page in Juno-Atom, but it cannot find the 'setobject!' method. 
Please help!

`using MeshCat
using GeometryTypes
using CoordinateTransformations

vis = Visualizer()

open(vis)

setobject!(vis, HyperRectangle(Vec(0., 0, 0), Vec(1., 1, 1)))
settransform!(vis, Translation(-0.5, -0.5, 0))`

ERROR:

┌ Info: MeshCat server started. You can open the visualizer by visiting the following URL in your browser:                      ort
└ http://127.0.0.1:8703                                          
ERROR: LoadError: MethodError: no method matching setobject!(::Visiisualizer, ::HyperRectangle{3, Float64})
Closest candidates are:
  setobject!(::AbstractVisualizer, ::GeometryLike) at C:\Users\AisiSUS\.julia\packages\MeshCat\GlCMx\src\abstract_visualizer.jl:21 
  setobject!(::AbstractVisualizer, ::GeometryLike, ::AbstractMaterial) at C:\Users\ASUS\.julia\packages\MeshCat\GlCMx\src\abstraisuct_visualizer.jl:29
  setobject!(::Visualizer, ::AbstractObject) at C:\Users\ASUS\.julia\packages\MeshCat\GlCMx\src\visualizer.jl:199               SUS
Stacktrace:                                                        
 [1] top-level scope                                            eri
   @ C:\Users\ASUS\AppData\Local\atom\app-1.57.0\scratch.jl:9   tis
 [2] eval
   @ .\boot.jl:360 [inlined]                                    uli
 [3] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094
in expression starting at C:\Users\ASUS\AppData\Local\atom\app-1 .57.0\scratch.jl:9
julia>

**Comment by ornithos** [comment]
@PratyushBhattacharya  I ran into the same thing - looks like the problem crops up from the switch from `GeometryTypes` ([deprecated](https://github.com/JuliaGeometry/GeometryTypes.jl)) to `GeometryBasics` ([commit 9feb28](https://github.com/rdeits/MeshCat.jl/commit/9feb28b98ef53f2003e11da00c27969b102d4d6e)). Both packages define many of the same types, but `GeometryLike` in MeshCat.jl is defined only for the latter package. Hence changing the example code in the README file as follows should do the trick:

```diff
- using GeometryTypes
+ using GeometryBasics
```

**Comment by ferrolho** [comment]
This issue has now been resolved. The only thing to note is that the contours example is not working because GeometryBasics.jl does not have a `SignedDistanceField` method, which GeometryTypes.jl used to have. I've captured this in issue https://github.com/rdeits/MeshCat.jl/issues/239, so I'm going to close this one.
