### ISSUE TITLE
Simple line and arrows

### ISSUE THREAD

**Issue by ga72kud** [rdeits/MeshCat.jl#217]
Hi, thank you for the excellent package. Is there a simple and fast solution for visualizing a line and arrows (should I use polygon of geometry basics?)? I want to visualize a point cloud and compute the nearest neighbor graph. 
3dimensional Line, in the documentation, is a 2dim line mentioned

**Comment by ga72kud** [comment]
Seems like to have use shaft = Cylinder(zero(Point{3, Float64}), Point(0.0, 0.0, 10.0), 0.1)
setobject!(vis, shaft)

**Comment by ferrolho** [comment]
Hi @ga72kud,

For simple line segments, you can use something like [this](https://github.com/JuliaRobotics/TORA.jl/blob/2e8c9f2b2b3547e6f9e0ac13395681a79855eb1d/src/constraints/end_effector.jl#L61-L66):
```julia
function show_path(vis::Visualizer, points::Matrix{Float64})
    points = collect(eachcol(points))
    material = LineBasicMaterial(color=colorant"yellow", linewidth=2.0)
    setobject!(vis["path"], Object(PointCloud(points), material, "Line"))
    nothing
end
```

For arrows, see this https://github.com/JuliaRobotics/RigidBodyDynamics.jl/issues/589#issuecomment-943176446.
