### ISSUE TITLE
Lift WebSockets.jl <1.6 compat constraint

### ISSUE THREAD

**Issue by ferrolho** [rdeits/MeshCat.jl#237]
https://github.com/rdeits/MeshCat.jl/pull/235 has constrained the upper bound of WebSockets.jl to <1.6, but this is not ideal and so we should find what are the required code changes to lift this constraint.

Note however that WebSockets.jl >=1.6 requires Julia >= 1.8.2 — see [WebSockets.jl/README.md > Upgrading to v1.6](https://github.com/JuliaWeb/WebSockets.jl/blob/811d94bcd23a6a5249f5b74b9989021fbe034629/README.md#upgrading-to-v-16).

**Comment by rdeits** [comment]
Closing--we no longer depend on WebSockets.jl at all as of #141
