### ISSUE TITLE
Is it possible to draw curves?

### ISSUE THREAD

**Issue by davibarreira** [rdeits/MeshCat.jl#253]
In three.js, I see that it is possible to draw curves, such as Beziers and Nurbs. Moreover, one can even draw curved surfaces. I was wondering if there is a way to do this using meshcat.

**Comment by ferrolho** [comment]
Hi Davi, you can draw curved lines (see [this comment](https://github.com/rdeits/MeshCat.jl/issues/217#issuecomment-1159409440) and an example [here](https://juliarobotics.org/TORA.jl/stable/tutorial/#Showing-the-Results)) and contours as well (see the [README example](https://github.com/rdeits/MeshCat.jl?tab=readme-ov-file#contours)).

**Comment by davibarreira** [comment]
Thanks for the answer @ferrolho . If I understood, is your solution for curved lines to divide in several line segments? I was looking for Bezier curves and the like.

**Comment by ferrolho** [comment]
Yes, you understood correctly — I sample a few points along the curved line I want to display, and then display it. It seems three.js supports quadratic bezier curves (see https://threejs.org/docs/#api/en/extras/curves/QuadraticBezierCurve), but I don't think this feature is exposed in MeshCat.jl. If you give it a go, please feel free to open a PR. Thanks!

**Comment by davibarreira** [comment]
Thanks, I'll try to do so.

**Comment by davibarreira** [comment]
@ferrolho , the implementation of curves should be done on MeshCat.jl or on the original meshcat library?

**Comment by ferrolho** [comment]
I am not sure why I missed your comment... So, apologies for the really long delay in replying. Exposing something from three.js to _meshcat_ will have to be done in the core library — https://github.com/meshcat-dev/meshcat. Then, once that is exposed, you should be able to use it from _MeshCat.jl_ or _meshcat-python_.
