### ISSUE TITLE
URL Not Loading

### ISSUE THREAD

**Issue by aaronbest123** [rdeits/MeshCat.jl#264]
I am getting an issue where the URL is never loading. I am trying to run the very basic code below, really appreciate any assistance you can provide.

```julia
using MeshCat

begin
	visualizer = Visualizer()
	open(visualizer)
	setvisible!(visualizer, true)
	wait(visualizer)
end
```

**Comment by ferrolho** [comment]
I have just tested the code snippet above with Julia v1.11.2 and MeshCat v1.1.0 and it works.

Can you provide a bit more information about what your setup looks like and what is not working?

Do you see the output below in the terminal when you run your snippet?
```
[ Info: Listening on: 127.0.0.1:8700, thread id: 1
┌ Info: MeshCat server started. You can open the visualizer by visiting the following URL in your browser:
└ http://127.0.0.1:8700
```

**Comment by aaronbest123** [comment]
Ended up just reinstalling all packages and it resolved itself!
