### ISSUE TITLE
update threejs

### ISSUE THREAD

**Issue by SimonDanisch** [rdeits/MeshCat.jl#54]
https://github.com/mrdoob/three.js/pull/14598 got merged :)

**Comment by rdeits** [comment]
Yup, that's exactly right. You'll then need to re-generate the javascript bundle, which requires that you have `npm` installed. Full steps would be:

1. Install `npm`
2. Install `yarn` by running `npm install -g yarn`
3. cd into the meshcat folder (the same folder where `package.json` lives)
4. Instantiate your JS development environment by running `yarn`
5. Generate the new javascript bundle (and watch for future changes) by running `npm run watch`

Also, if you want to play around with the `meshcat` repo inside of `MeshCat.jl`, I'd suggest first running:

```julia
julia> MeshCat.develop_meshcat_assets()
```

which will convert the downloaded meshcat assets into a proper git submodule.

**Comment by SimonDanisch** [comment]
So how does this work, if there is no tagged version?

**Comment by rdeits** [comment]
Uh, that's a great question. Maybe https://docs.npmjs.com/files/package.json#git-urls-as-dependencies ?

**Comment by SimonDanisch** [comment]
Almost there:
```
sd@simondanisch:~/juliastuff/meshcat$ npm run watch
npm ERR! Linux 4.15.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2

npm ERR! missing script: watch
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sd/juliastuff/meshcat/npm-debug.log
```

**Comment by rdeits** [comment]
Ah, sorry, "build" not "watch"

**Comment by ferrolho** [comment]
I have tested `threejs` _r109_ (https://github.com/ferrolho/meshcat/commit/f020e532a585b40443757ca027f3692980598359) and, at first sight, it does not seem to have breaking changes. Is there a reason for not upgrading?

**Comment by rdeits** [comment]
Nope, let's do it! I've made the necessary minor changes to meshcat over in https://github.com/rdeits/meshcat/pull/63 . I just need to test those changes against the Julia and Python clients, and then we should be good to go.

**Comment by ferrolho** [comment]
Three is now on _r110_ (https://www.npmjs.com/package/three). Would you like me to update my branch and create a new PR here?

**Comment by rdeits** [comment]
I included r110 in https://github.com/rdeits/meshcat/pull/63 so I think that should already cover it
