### ISSUE TITLE
using PointsMaterial

### ISSUE THREAD

**Issue by pvazteixeira** [rdeits/MeshCat.jl#58]
Trying to control the size of the points in a PointCloud using `PointsMaterial`, I'm getting several triangles in the viewer instead:

![triangles](https://screenshotscdn.firefoxusercontent.com/images/7d760aed-dc4a-4aa6-ad15-075d4e0a0666.png)

Here's the code I used:

```julia
using MeshCat
vis = Visualizer()
open(vis)

using ColorTypes, GeometryTypes
material = PointsMaterial(color=RGBA(0,0,1,0.5))
verts =rand(Point3f0,100)
setobject!(vis[:PointCloud],PointCloud(verts),material)
```

**Comment by rdeits** [comment]
Ah, sorry about that. Can you try `setobject!(..., Points(PointCloud(verts), material)))` ?

**Comment by pvazteixeira** [comment]
That works, thanks! I was following the `setobject!(vis, obj, material)` syntax from the example.

**Comment by rdeits** [comment]
Yeah, that's reasonable. I'll fix this.
