### ISSUE TITLE
Programmatically Take Pictures

### ISSUE THREAD

**Issue by ryanelandt** [rdeits/MeshCat.jl#61]
This new visualizer is a lot lighter than DrakeVisualizer; well done!

I want to take pictures from this visualizer programmatically, but don't see a way to do this. I saw the animation demo, but it's not what I'm looking for. Is there a way to trigger the "save_image" button and save the image into a destination of your choice? I have something like `save_mesh_cat_image("/home/rdeits/Downloads/image0001.png")` in mind.

**Comment by PikaPei** [comment]
Hi, I just wonder that is it possible to implement the function of saving the image?
Thanks!

**Comment by traikodinev** [comment]
+1. This might be difficult, due to having to open it in a browser. Perhaps a browser extension can do it?

**Comment by ga72kud** [comment]
I can show it in Plots, display(render(vis))

But with savefig(..) it does not work

**Comment by ferrolho** [comment]
This was added with https://github.com/rdeits/MeshCat.jl/pull/195.
