### ISSUE TITLE
Compatibility with WebIO 0.6

### ISSUE THREAD

**Issue by rdeits** [rdeits/MeshCat.jl#71]
Looks like WebIO 0.6 breaks MeshCat a little bit. Basic visualizations seem to work, but: 

- [ ] `wait(vis)` blocks forever
- [ ] `iframe(vis)` throws a MethodError

All of these look like cases where I was digging around inside the internals of WebIO, so I'm not too surprised.

**Comment by rdeits** [comment]
ref https://github.com/JuliaGizmos/WebIO.jl/issues/225

**Comment by tkoolen** [comment]
Close?

**Comment by rdeits** [comment]
Actually, no :-/. WebIO v0.7 is actually just WebIO v0.4.3 again (essentially reverting v0.6). There are more changes in the pipeline (which will become WebIO v0.8), but I haven't adapted to them yet. 

So, I guess since we're never going to support WebIO 0.6, we could close this, but perhaps we should just rename it to whatever the actual version of WebIO we care about is...

**Comment by tkoolen** [comment]
Oh I see, thanks.

**Comment by rdeits** [comment]
Closing in favor of webio 0.8 support
