### ISSUE TITLE
meshcat.zip not found in Windows

### ISSUE THREAD

**Issue by phelipe** [rdeits/MeshCat.jl#77]
Building MeshCat in Windows returns : 
```
Error: The system can not find the file specified.
C:\Users\phelipe\AppData\Local\Temp\jl_381D.tmp\meshcat.zip
```

**Comment by phelipe** [comment]
Solved.

**Comment by rdeits** [comment]
Did you identify the problem? If so, then describing how you resolved it will probably be helpful for future users who might experience the same issue.

**Comment by phelipe** [comment]
I downloaded the zip directly and unzipped, but I suspect the problem was the antivirus that was blocking some of julia operations.
