### ISSUE TITLE
Breaking Juno

### ISSUE THREAD

**Issue by bjack205** [rdeits/MeshCat.jl#85]
When installing this in Juno, I get a compatibility problem for WebIO with Atom 0.7.12. If I downgrade to Atom 0.7.10 and then install MeshCat I loose auto-completion support in Atom/Juno, which is really frustrating, especially since I can't use unicode anymore.

**Comment by rdeits** [comment]
Ah, interesting. I had to add a version cap on MeshCat's compatibility with WebIO, but I think that newer versions of WebIO should be working again. I'll try the latest WebIO and see if it works--if it does, then this should be compatible with Juno and Atom again.

**Comment by rdeits** [comment]
I believe this should be fixed in the master branch of MeshCat. I'll tag a new release shortly, and that should fix the compatibility with WebIO and Atom. Until that release comes out, you should be able to do: 

```julia
pkg> add MeshCat#master
```

to get the latest version of MeshCat with WebIO 0.7 compatibility.

**Comment by bjack205** [comment]
Awesome, that fixed it!
Thanks!
