### ISSUE TITLE
Draw PolyLine

### ISSUE THREAD

**Issue by Affie** [rdeits/MeshCat.jl#87]
Is there a `PolyLine` that draws a continuous line. Like `LineSegments`, but connecting everything.

**Comment by rdeits** [comment]
Yes, I think that's supported in threejs, so we'd just need to expose it in MeshCat. Until then, you can still construct one through the basic `MeshCat.Object` constructor: 

```julia
using MeshCat, GeometryTypes
coordinates = [Point(0., 0, 0), Point(1., 0, 0), Point(1., 1., 0)]
vis = Visualizer()
setobject!(vis, Object(PointCloud(coordinates), LineBasicMaterial(), "Line"))
```

Likewise, you should be able to create a line loop by changing `"Line"` to `"LineLoop"`. That string just needs to match the name of the Three.js class you want to create (like https://threejs.org/docs/index.html#api/en/objects/Line or https://threejs.org/docs/index.html#api/en/objects/LineSegments ). 

It should also be easy to add some helper methods to make creating lines less verbose.

**Comment by Affie** [comment]
thank you
