### ISSUE TITLE
Meshing lower bound of 0.3.0 in REQUIRE before registering?

### ISSUE THREAD

**Issue by tkoolen** [rdeits/MeshCat.jl#9]
Not a huge deal, but I was running `Pkg.test("MeshCat")` locally, and it errored on `MarchingTetrahedra`. I checked my version of Meshing, and it's 0.2.0. I see that the Meshing 0.3.0 PR is not yet merged.

**Comment by rdeits** [comment]
Ah yeah, Meshing 0.3 is required for the notebook test to pass. Should be OK as long as the Meshing 0.3 PR is merged before the MeshCat registration PR. If that doesn't get merged, though, then I'll have to update the notebook. Thanks!
