### ISSUE TITLE
Using MeshCat inside Pinocchio

### ISSUE THREAD

**Issue by jcarpent** [rdeits/MeshCat.jl#91]
Dear @rdeits,

After some discussions with [Pinocchio](https://github.com/stack-of-tasks/pinocchio) users and developers (see stack-of-tasks/pinocchio#657 and stack-of-tasks/pinocchio#662), we plan to integrate your lightweight and excellent viewer inside the Pinocchio setup.

We have some requested features, like the support of STL and DAE objects among others.

Can you tell us what is your current roadmap, the future status of MeshCat and the way you may see how the collaboration can work?

**Comment by rdeits** [comment]
Hi Justin! That's great to hear. I think this can definitely work. I'm not actively working on any new features for meshcat, but I'm using it frequently and trying to make sure that it stays useful and up-to-date. 

As for DAE and STL support, it looks like there are already Three.js loader plugins for those file types, so I think we could support them pretty easily in the same way as OBJ files. 

Please feel free to open github issues for problems or feature requests. It will make my life a bit easier if you open issues related to the web frontend over at https://github.com/rdeits/meshcat and issues related to the python interface at https://github.com/rdeits/meshcat-python . I can't promise that I'll have a lot of time to implement new features on my own, but I'm happy to help as much as I can, and pull requests are extremely welcome.

**Comment by jcarpent** [comment]
@rdeits Thanks for this quick reply and all these details.
I totally understand the decrease of additional features as the project seems to be mature enough!
Anyway, thanks alot for this very nice framework.
