### ISSUE TITLE
IJuliaCell seems to be broken

### ISSUE THREAD

**Issue by rdeits** [rdeits/MeshCat.jl#94]
I don't get any output at all, just a blank white frame. 

Possibly related to https://github.com/JuliaGizmos/WebIO.jl/issues/225, although I thought that issue should not affect WebIO 0.7.

**Comment by rdeits** [comment]
I'm hoping to wait for https://github.com/JuliaGizmos/WebIO.jl/pull/242 before I spend too much time on this.

**Comment by rdeits** [comment]
Actually, it looks like it's not related to https://github.com/JuliaGizmos/WebIO.jl/issues/225 since I can indeed render MeshCat inside an iframe when not using Jupyter....

**Comment by rdeits** [comment]
Uh, now I'm more confused than ever. It actually works fine. 

Maybe my notebooks were running with the wrong Julia kernel and not actually getting the right package versions? In any case, I guess I can close this issue and revisit it when the new WebIO comes in.

**Comment by tkoolen** [comment]
Ah yeah, I've been bitten by that a couple of times. I honestly wish the Julia version number weren't embedded in the notebook.
